// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TogbilletterOblig3.Models;

namespace TogbilletterOblig3.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20191115114826_FAQSporsmalAdded")]
    partial class FAQSporsmalAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TogbilletterOblig3.Models.Sporsmal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sporsmaler");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            sp = "Hvorfor går ikke toget fra stasjonen min?"
                        },
                        new
                        {
                            ID = 2,
                            sp = "Hvordan kjøper jeg billett?"
                        },
                        new
                        {
                            ID = 3,
                            sp = "Noe gikk galt med bestillingen min. Hva gjør jeg?"
                        },
                        new
                        {
                            ID = 4,
                            sp = "Kan jeg ta med barnevogn?"
                        },
                        new
                        {
                            ID = 5,
                            sp = "Jeg ble trukket penger, men fikk ingen billett?"
                        });
                });

            modelBuilder.Entity("TogbilletterOblig3.Models.Svar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("svar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Svarer");
                });
#pragma warning restore 612, 618
        }
    }
}
