// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TogbilletterOblig3.Models;

namespace TogbilletterOblig3.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20191115163352_FAQSporsmalOgSvarUpdate")]
    partial class FAQSporsmalOgSvarUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TogbilletterOblig3.Models.Sporsmal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("antallStemmer")
                        .HasColumnType("int");

                    b.Property<int>("poeng")
                        .HasColumnType("int");

                    b.Property<string>("sp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sporsmaler");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            antallStemmer = 0,
                            poeng = 0,
                            sp = "Hvorfor går ikke toget fra stasjonen min?"
                        },
                        new
                        {
                            ID = 2,
                            antallStemmer = 0,
                            poeng = 0,
                            sp = "Hvordan kjøper jeg billett?"
                        },
                        new
                        {
                            ID = 3,
                            antallStemmer = 0,
                            poeng = 0,
                            sp = "Noe gikk galt med bestillingen min. Hva gjør jeg?"
                        },
                        new
                        {
                            ID = 4,
                            antallStemmer = 0,
                            poeng = 0,
                            sp = "Kan jeg ta med barnevogn?"
                        },
                        new
                        {
                            ID = 5,
                            antallStemmer = 0,
                            poeng = 0,
                            sp = "Jeg ble trukket penger, men fikk ingen billett?"
                        });
                });

            modelBuilder.Entity("TogbilletterOblig3.Models.Svar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SporsmalID")
                        .HasColumnType("int");

                    b.Property<int>("antallStemmer")
                        .HasColumnType("int");

                    b.Property<int>("poeng")
                        .HasColumnType("int");

                    b.Property<string>("svar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SporsmalID");

                    b.ToTable("Svarer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            antallStemmer = 0,
                            poeng = 0,
                            svar = "Vi jobber hele tiden med å utvide tilbudet vårt. Beklager for eventuelle problemer."
                        },
                        new
                        {
                            ID = 2,
                            antallStemmer = 0,
                            poeng = 0,
                            svar = "Du kan gå inn på nettsiden vår og kjøpe billetter."
                        },
                        new
                        {
                            ID = 3,
                            antallStemmer = 0,
                            poeng = 0,
                            svar = "Du kan sende epost til oss på Togbillett@Kundeservice.no"
                        },
                        new
                        {
                            ID = 4,
                            antallStemmer = 0,
                            poeng = 0,
                            svar = "Ja alle togene våres har mulighet for barnevogn."
                        },
                        new
                        {
                            ID = 5,
                            antallStemmer = 0,
                            poeng = 0,
                            svar = "Send oss bilde av betalingen på epost, så skal vi fikse det."
                        });
                });

            modelBuilder.Entity("TogbilletterOblig3.Models.Svar", b =>
                {
                    b.HasOne("TogbilletterOblig3.Models.Sporsmal", null)
                        .WithMany("svar")
                        .HasForeignKey("SporsmalID");
                });
#pragma warning restore 612, 618
        }
    }
}
