// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TogbilletterOblig3.Models;

namespace TogbilletterOblig3.Migrations
{
    [DbContext(typeof(DB))]
    partial class DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TogbilletterOblig3.Models.Sporsmal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sporsmalNr")
                        .HasColumnType("int");

                    b.Property<string>("svar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("totalOppStemmer")
                        .HasColumnType("int");

                    b.Property<int>("totalStemmer")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Sporsmaler");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            sp = "Hvorfor går ikke toget fra stasjonen min?",
                            sporsmalNr = 1,
                            svar = "Vi jobber hele tiden med å utvide tilbudet vårt. Beklager for eventuelle problemer.",
                            totalOppStemmer = 0,
                            totalStemmer = 0
                        },
                        new
                        {
                            ID = 2,
                            sp = "Hvordan kjøper jeg billett?",
                            sporsmalNr = 2,
                            svar = "Du kan gå inn på nettsiden vår og kjøpe billetter.",
                            totalOppStemmer = 0,
                            totalStemmer = 0
                        },
                        new
                        {
                            ID = 3,
                            sp = "Noe gikk galt med bestillingen min. Hva gjør jeg?",
                            sporsmalNr = 3,
                            svar = "Du kan sende epost til oss på Togbillett@Kundeservice.no",
                            totalOppStemmer = 0,
                            totalStemmer = 0
                        },
                        new
                        {
                            ID = 4,
                            sp = "Kan jeg ta med barnevogn?",
                            sporsmalNr = 4,
                            svar = "Ja alle togene våres har mulighet for barnevogn.",
                            totalOppStemmer = 0,
                            totalStemmer = 0
                        },
                        new
                        {
                            ID = 5,
                            sp = "Jeg ble trukket penger, men fikk ingen billett?",
                            sporsmalNr = 5,
                            svar = "Send oss bilde av betalingen på epost, så skal vi fikse det.",
                            totalOppStemmer = 0,
                            totalStemmer = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
